/* Publication data for both sides of the card.
 *
 * math   — one chronological list, newest first. NEW WORKS GO AT THE TOP of the array;
 *          numbering on the card is continuous and generated by the <ol>.
 * priest — reports, articles and interviews, also one chronological list, newest first
 *          (undated items last); `group` is shown as a small type tag.
 *
 * Entry fields (math):
 *   year, title, venue, pages, coauthors, manuscript (bool),
 *   kind ('article'|'book'|'thesis'|'abstract'|'preprint'),
 *   translation: { title, venue } | null   — the English-edition version of the same paper
 *   links:   [ { label, url } ]
 *   indexed: [ 'scopus' | 'wos' | 'rsci' | 'mathnet' | 'zbmath' | 'mathscinet' ]
 *            Only indexes that were actually verified are listed: Scopus/WoS are claimed
 *            solely for the Springer edition of the 2002 paper (DOI 10.1023/A:1014914701477);
 *            Math-Net.Ru / zbMATH / MathSciNet come from person34113, api.zbmath.org and
 *            MR Author ID 641320; РИНЦ from the ИСТИНА profile (worker 178258660).
 *
 * Entry fields (priest):
 *   year (or null), date, group ('reports'|'articles'|'interviews'),
 *   title: { ru, en }, venue: { ru, en }, url, related: [ { label: {ru,en}, url } ]
 *
 * Titles and venues stay in their original language on both sides of the card;
 * only labels, type tags and index badges are localized.
 */
window.PUBLICATIONS = {
  math: [
    {
      year: 2025, kind: 'book',
      title: 'Дополнительные главы функционального анализа в примерах и задачах: учебник',
      venue: 'М.: МАКС Пресс, 2025. — 188 с. — ISBN 978-5-317-07491-3',
      pages: 188,
      coauthors: 'Коровина М. В., Григорянц С. А., Смирнов И. Н., Аристов А. И.',
      manuscript: false,
      translation: null,
      links: [
        { label: 'DOI', url: 'https://doi.org/10.29003/m4823.978-5-317-07491-3' },
        { label: 'ИСТИНА', url: 'https://istina.msu.ru/workers/178258660/publications/' }
      ],
      indexed: ['rsci']
    },
    {
      year: 2020, kind: 'preprint',
      title: 'On the model of hyperrational numbers with selective ultrafilter',
      venue: 'arXiv:2004.01674 [math.LO], 2020 (earlier version: Preprints.org, 2019)',
      pages: null, coauthors: '', manuscript: false, translation: null,
      links: [
        { label: 'arXiv', url: 'https://arxiv.org/abs/2004.01674' },
        { label: 'Preprints.org', url: 'https://doi.org/10.20944/preprints201902.0273.v1' },
        { label: 'zbMATH', url: 'https://zbmath.org/900426765' }
      ],
      indexed: ['zbmath']
    },
    {
      year: 2011, kind: 'article',
      title: 'О конфигурационных комплексах семейства подпространств линейного пространства',
      venue: 'Российско-Армянский (Славянский) университет. Вестник. Физико-математические и естественные науки. № 2, 2011 г., с. 9–18',
      pages: 10, coauthors: '', manuscript: false, translation: null,
      links: [{ label: 'ИСТИНА', url: 'https://istina.msu.ru/workers/178258660/publications/' }],
      indexed: ['rsci']
    },
    {
      year: 2003, kind: 'article',
      title: 'Об одном новом классе двоичных кодов, исправляющих ошибки',
      venue: 'Известия НАН Армении. Математика. Том 38, № 2, 2003 г., с. 29–36',
      pages: 8, coauthors: '', manuscript: false, translation: null,
      links: [
        { label: 'Math-Net.Ru', url: 'https://www.mathnet.ru/rus/person34113' },
        { label: 'zbMATH', url: 'https://zbmath.org/5546078' }
      ],
      indexed: ['mathnet', 'zbmath']
    },
    {
      year: 2003, kind: 'article',
      title: 'Об одном случае достижимости границы расстояния для фрактальных кодов',
      venue: 'Доклады НАН Армении. Математика. Том 103, № 3, 2003 г., с. 216–220',
      pages: 5, coauthors: '', manuscript: false, translation: null,
      links: [{ label: 'Math-Net.Ru', url: 'https://www.mathnet.ru/rus/person34113' }],
      indexed: ['mathnet']
    },
    {
      year: 2003, kind: 'article',
      title: 'On a new class of binary error correcting codes',
      venue: 'Journal of Contemporary Mathematical Analysis (Armenian Academy of Sciences). Vol. 38, № 2, 2003, pp. 26–34',
      pages: 9, coauthors: '', manuscript: false, translation: null,
      links: [{ label: 'zbMATH', url: 'https://zbmath.org/5546078' }],
      indexed: ['zbmath']
    },
    {
      year: 2003, kind: 'article',
      title: 'On a case of fractal codes distance upper boundary reaching',
      venue: 'National Academy of Sciences of Armenia. Reports. Mathematics. Vol. 103, № 3, 2003',
      pages: 5, coauthors: '', manuscript: false, translation: null, links: [], indexed: []
    },
    {
      year: 2002, kind: 'article',
      title: 'Определение фенольных альдегидов в коньяках и винах методом капиллярного электрофореза: новые маркеры качества коньяка',
      venue: 'Журнал аналитической химии. 2002, том 57, № 4, с. 422–428',
      pages: 7, coauthors: 'Паносян А. Г., Мамиконян Г., Оганесян А. и др.',
      manuscript: false,
      translation: {
        title: 'Determination of phenolic aldehydes in cognacs and wines by capillary electrophoresis: new cognac quality markers',
        venue: 'Journal of Analytical Chemistry, 57:4 (2002), pp. 356–361 (Panosyan A. G., Mamikonyan G., Torosyan M., Abramyan A., Oganesyan A., Gabrielyan E. S., Grigoryants A., Mkhitaryan S., Lapin B. V.)'
      },
      links: [{ label: 'DOI', url: 'https://doi.org/10.1023/A:1014914701477' }],
      indexed: ['scopus', 'wos', 'rsci']
    },
    {
      year: 2002, kind: 'abstract',
      title: 'Determination of an apparent age of brandy using phenolic aldehydes as markers',
      venue: 'ISAAC Conference on Complex Analysis, Differential Equations and Related Topics, September 17–21, 2002, Yerevan, p. 25',
      pages: 1, coauthors: '', manuscript: false, translation: null, links: [], indexed: []
    },
    {
      year: 2001, kind: 'article',
      title: 'Определение возраста коньяка путем анализа содержания фенольных альдегидов',
      venue: 'Лекарства и медицина. № 3. Ереван, 2001 г., с. 53–60',
      pages: 8, coauthors: 'Торосян М., Паносян А. Г., Абрамян А. и др.',
      manuscript: false, translation: null, links: [], indexed: []
    },
    {
      year: 1999, kind: 'thesis',
      title: 'Тензорное и дифференциальное исчисление в категориях и их применение в теории дифференциальных уравнений в частных производных',
      venue: 'Диссертация на соискание учёной степени кандидата физико-математических наук (01.01.02, 01.01.04), ЕГУ, октябрь 1999 г. Научные руководители: С. Г. Далалян, И. А. Мирзоян',
      pages: 70, coauthors: '', manuscript: true, translation: null,
      links: [{ label: 'ИСТИНА', url: 'https://istina.msu.ru/workers/178258660/all/' }],
      indexed: []
    },
    {
      year: 1999, kind: 'thesis',
      title: 'Тензорное и дифференциальное исчисление в категориях и их применение в теории дифференциальных уравнений в частных производных',
      venue: 'Автореферат диссертации, ЕГУ, октябрь 1999 г.',
      pages: 15, coauthors: '', manuscript: true, translation: null, links: [], indexed: []
    },
    {
      year: 1998, kind: 'article',
      title: 'Об одной интерпретации тензора кручения связности',
      venue: 'Известия вузов. Математика. 1998, № 8 (435), с. 22–28',
      pages: 7, coauthors: '', manuscript: false,
      translation: {
        title: 'On an interpretation of the torsion tensor of a connection',
        venue: 'Russian Mathematics (Iz. VUZ), 42:8 (1998), pp. 20–26'
      },
      links: [
        { label: 'PDF', url: 'https://kpfu.ru/portal/docs/F603979822/e03_8.pdf' },
        { label: 'Math-Net.Ru', url: 'https://www.mathnet.ru/rus/person34113' },
        { label: 'zbMATH', url: 'https://zbmath.org/2133870' },
        { label: 'MathSciNet', url: 'https://mathscinet.ams.org/mathscinet/article?mr=1657370' }
      ],
      indexed: ['mathnet', 'zbmath', 'mathscinet', 'rsci']
    },
    {
      year: 1998, kind: 'article',
      title: 'Локальные свойства дифференциальных операторов в категории модулей',
      venue: 'Известия НАН Армении. Математика. Том 33, № 5, 1998 г., с. 22–29',
      pages: 8, coauthors: '', manuscript: false,
      translation: {
        title: 'Local properties of differential operators in categories of modules',
        venue: 'Journal of Contemporary Mathematical Analysis (Armenian Academy of Sciences), 33:5 (1998), pp. 1–8'
      },
      links: [
        { label: 'Math-Net.Ru', url: 'https://www.mathnet.ru/rus/person34113' },
        { label: 'zbMATH', url: 'https://zbmath.org/1586201' }
      ],
      indexed: ['mathnet', 'zbmath']
    },
    {
      year: 1998, kind: 'abstract',
      title: 'Локальные свойства дифференциальных операторов в категории модулей',
      venue: 'Международная школа-семинар по геометрии и анализу памяти Н. В. Ефимова. Абрау-Дюрсо, 5–11 сентября 1998 г. Тезисы докл., с. 188–189',
      pages: 2, coauthors: '', manuscript: false, translation: null, links: [], indexed: []
    },
    {
      year: 1997, kind: 'abstract',
      title: 'Тензорные произведения в категориях',
      venue: 'Международный геометрический семинар имени Н. И. Лобачевского. Казань, 4–6 февраля 1997 г. Тезисы докл., с. 37',
      pages: 1, coauthors: '', manuscript: false, translation: null, links: [], indexed: []
    },
    {
      year: 1996, kind: 'abstract',
      title: 'О тензоре кручения',
      venue: 'Международная геометрическая школа-семинар памяти Н. В. Ефимова. Абрау-Дюрсо, 27 сент. – 4 окт. 1996 г. Тезисы докл., с. 13–14',
      pages: 2, coauthors: '', manuscript: false, translation: null, links: [], indexed: []
    }
  ],

  priest: [
    {
      year: 2019, date: '2019-12-12', group: 'interviews',
      title: { ru: '«Семья должна стать субъектом права!»', en: '“The Family Must Become a Subject of Law!”' },
      venue: {
        ru: 'Интервью, беседовал Андрей Сегеда. Православие.fm, 12 декабря 2019 г.',
        en: 'Interview by Andrey Segeda. Pravoslavie.fm, 12 December 2019'
      },
      url: 'https://pravoslavie.fm/interview/protoierej-arsenij-grigoryancz-semya-dolzhna-stat-subektom-prava/',
      related: []
    },
    {
      year: 2018, date: '2018-01-24', group: 'reports',
      title: {
        ru: 'Семья — основа традиционной системы ценностей',
        en: 'The Family as the Foundation of the Traditional System of Values'
      },
      venue: {
        ru: 'Доклад на XXVI Международных Рождественских образовательных чтениях «Нравственные ценности и будущее человечества». Москва, 24–26 января 2018 г.',
        en: 'Report at the XXVI International Christmas Educational Readings “Moral Values and the Future of Humanity”. Moscow, 24–26 January 2018'
      },
      url: 'https://rnsa.armeparchy.org/ideology/semya-osnova-tsennostey',
      related: [
        {
          label: { ru: '«Не отчуждайтесь!» — Православие.Ru, 29.01.2018', en: '“Do not become estranged!” — Pravoslavie.Ru, 29 Jan 2018' },
          url: 'https://pravoslavie.ru/110218.html'
        }
      ]
    },
    {
      year: 2016, date: '2016-11-01', group: 'reports',
      title: {
        ru: 'Роль России на мировой арене: на страже традиционных ценностей',
        en: 'Russia’s Role on the World Stage: Guarding Traditional Values'
      },
      venue: {
        ru: 'Доклад на XX Всемирном русском народном соборе «Россия и Запад: диалог народов в поисках ответов на цивилизационные вызовы». Москва, 1 ноября 2016 г.',
        en: 'Report at the XX World Russian People’s Council “Russia and the West: a Dialogue of Peoples in Search of Answers to Civilizational Challenges”. Moscow, 1 November 2016'
      },
      url: 'https://rnsa.armeparchy.org/ideology/vrns-20-rol-rossii',
      related: []
    },
    {
      year: 2015, date: '2015-11-10', group: 'reports',
      title: { ru: 'О вере и науке', en: 'On Faith and Science' },
      venue: {
        ru: 'Доклад на XIX Всемирном русском народном соборе «Наследие князя Владимира и судьбы исторической Руси». Москва, 10 ноября 2015 г.',
        en: 'Report at the XIX World Russian People’s Council “The Legacy of Prince Vladimir and the Destiny of Historical Rus’”. Moscow, 10 November 2015'
      },
      url: 'https://rnsa.armeparchy.org/ideology/vrns-19-o-vere-i-nauke',
      related: []
    },
    {
      year: 2015, date: '2015-07-22', group: 'interviews',
      title: {
        ru: 'Понять Армению: о христианстве, протестах в Ереване и том, ради чего стоит выходить на митинг',
        en: 'Understanding Armenia: on Christianity, the Protests in Yerevan and What Is Worth Rallying For'
      },
      venue: {
        ru: 'Интервью, беседовала Дарья Менделеева. Правмир, 22 июля 2015 г.',
        en: 'Interview by Daria Mendeleeva. Pravmir, 22 July 2015'
      },
      url: 'https://www.pravmir.ru/protoierey-arseniy-grigoryants-pravoslavie-v-armenii-osobennosti-zhizni-v-menshinstve/',
      related: []
    },
    {
      year: 2014, date: '2014-12-01', group: 'articles',
      title: {
        ru: 'К обсуждению Декларации русской идентичности. Русские: народ-цивилизация',
        en: 'On the Declaration of Russian Identity. Russians: a People-Civilization'
      },
      venue: {
        ru: 'Статья, декабрь 2014 г. — отклик на Декларацию русской идентичности, принятую XVIII Всемирным русским народным собором 11 ноября 2014 г.',
        en: 'Article, December 2014 — a response to the Declaration of Russian Identity adopted by the XVIII World Russian People’s Council on 11 November 2014'
      },
      url: 'https://rnsa.armeparchy.org/ideology/russkie-narod-tsivilizatsiya',
      related: []
    },
    {
      year: 2012, date: '2012-10-01', group: 'reports',
      title: {
        ru: 'Концепция цивилизаций и национальная идея',
        en: 'The Concept of Civilizations and the National Idea'
      },
      venue: {
        ru: 'Доклад на XVI Всемирном русском народном соборе «Рубежи истории — рубежи России». Москва, 1–2 октября 2012 г.',
        en: 'Report at the XVI World Russian People’s Council “Frontiers of History — Frontiers of Russia”. Moscow, 1–2 October 2012'
      },
      url: 'https://rnsa.armeparchy.org/ideology/vrns-16-natsionalnaya-ideya',
      related: []
    },
    {
      year: null, date: null, group: 'articles',
      title: { ru: 'Цивилизация, культура, этнос', en: 'Civilization, Culture, Ethnos' },
      venue: {
        ru: 'Программный текст Русского народного собора в Армении',
        en: 'Programme text of the Russian People’s Council in Armenia'
      },
      url: 'https://rnsa.armeparchy.org/ideology/tsivilizatsiya-kultura-etnos',
      related: []
    },
    {
      year: null, date: null, group: 'articles',
      title: { ru: 'Для кого и для чего создан РНСА?', en: 'For Whom and for What Was the RPCA Created?' },
      venue: {
        ru: 'Программный текст Русского народного собора в Армении',
        en: 'Programme text of the Russian People’s Council in Armenia'
      },
      url: 'https://rnsa.armeparchy.org/ideology/dlya-kogo-i-dlya-chego-sozdan-rnsa',
      related: []
    }
  ]
};
